// <auto-generated />
namespace Sample_Project_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEdited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEdited));
        
        string IMigrationMetadata.Id
        {
            get { return "201903152139091_AddEdited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
